### ISSUE TITLE
Use of single quotes

### ISSUE THREAD

**Issue by aaubry** [perlpunk/yaml-test-schema#2]
I noticed that in the tests, when scalars are quoted, single quotes are used. Is there any part of the spec that suggests using that style, or is it an arbitrary decision ? Note that single quotes are not valid in JSON. Wouldn't double quotes be a more sensible choice ?

https://github.com/perlpunk/yaml-test-schema/blob/63558dd730d378362a09a0358bf7ff4a9d29045c/yaml-schema.yaml#L81

**Comment by perlpunk** [comment]
That's the recommended quoting style, because strings in single quotes are pretty much literal (except for the double escaping `''`).
Using double quotes is IMHO a sign that there might be escaping characters in there, so I use them only when I need escapes.

But you're right, that's not in the spec.
But @ingydotnet agrees with this, and also we have the same quoting styles in perl, and here we also recommend using single quotes by default, unless we need escape sequences or interpolation.

Regarding JSON, I'm not sure I should limit myself to JSON's only quoting style ;-)

**Comment by aaubry** [comment]
I agree that this is a sensible choice, except when using the JSON schema, that's why I mentioned it. I would expect that by using the JSON schema my output would be valid JSON.

**Comment by perlpunk** [comment]
Ok, that might be confusing, but using the JSON Schema doesn't influence the syntax. It's only about resolving/serializing booleans/numbers etc.

I guess in the most cases one can just use an existing JSON library to output JSON.

**Comment by aaubry** [comment]
Ok, thanks for the clarification.
